
/* ===== IITH slot grid — official, from iith.ac.in timetable template ===== */
var DAYS=["Mon","Tue","Wed","Thu","Fri"];
var ROWS=["09:00","10:00","11:00","12:00","14:30","16:00"];
var ROWLBL={"09:00":"09:00–09:55","10:00":"10:00–10:55","11:00":"11:00–11:55",
            "12:00":"12:00–12:55","14:30":"14:30–15:55","16:00":"16:00–17:25"};
var SLOTS={
  A:[[0,"09:00"],[2,"11:00"],[3,"10:00"]],
  B:[[0,"10:00"],[2,"09:00"],[3,"11:00"]],
  C:[[0,"11:00"],[2,"10:00"],[3,"09:00"]],
  D:[[0,"12:00"],[1,"09:00"],[4,"11:00"]],
  E:[[1,"10:00"],[3,"12:00"],[4,"09:00"]],
  F:[[1,"11:00"],[4,"10:00"],[2,"14:30"]],
  G:[[1,"12:00"],[2,"12:00"],[4,"12:00"]],
  P:[[0,"14:30"],[3,"16:00"]],
  Q:[[0,"16:00"],[3,"14:30"]],
  R:[[1,"14:30"],[4,"16:00"]],
  S:[[1,"16:00"],[4,"14:30"]]
};

/* ===== EM M.Tech Techno-Entrepreneurship curriculum =====
   Source: em.iith.ac.in/mtech_program.html + live AIMS Jul–Nov 2026 data.
   st: "ok" verified registerable in AIMS | "blocked" running but missing from picker
       "off" not running this term | "noslot" registerable but no slot published    */
var CUR={
 1:{ label:"Semester 1", total:14, note:"Plus the mandatory non-credit Clean India course, handled separately by NSS.", groups:[
   {id:"core", name:"Core (EM)", need:9, rule:"All three are compulsory. 3 + 3 + 3.", courses:[
     ["EM5090","Accounting and Finance for Entrepreneurs",3,"Q","Dr. Ranapratap Maradana","MAE-LH-6","ok"],
     ["EM5110","Foundations of Techno-Entrepreneurship",3,"G","Dr. Jayshree Patnaik","MAE-LH-10","ok"],
     ["EM5270","Entrepreneurial Marketing",3,"R","Dr. Rajesh Ittamalla","LHC-11","ok"]
   ]},
   {id:"mgmt", name:"Department electives", need:2, rule:"Pick any two. 1 + 1.", courses:[
     ["EM5020","Innovation Management",1,"P","Dr. Nakul Parameswar","LHC-14","ok"],
     ["EM5040","Game Theory for Startups",1,"E","Dr. L. M. Maiyar","MAE-LH-10","ok"],
     ["EM5120","Economics for Technocrats",1,"","Dr. Ranapratap Maradana","\u2014","noslot"],
     ["LA1260","Fundamentals of Organizational Structure",1,"","\u2014","\u2014","noslot"]
   ]},
   {id:"eng", name:"Engineering elective", need:3, rule:"One 3-credit course offered by another department. Course code must start with 5 or 6. Not Design, Physics, Chemistry or Maths.", eng:true, courses:[]}
 ]},
 2:{ label:"Semester 2", total:14, note:"Industry Lecture and Communication Skills are both mandatory in this semester.", groups:[
   {id:"core", name:"Core (EM)", need:7, rule:"All three are compulsory. 3 + 3 + 1.", courses:[
     ["EM6040","Operational Entrepreneurship",3,"","\u2014","\u2014","next"],
     ["EM6010","Strategic Management",3,"","\u2014","\u2014","next"],
     ["EM6130","Introduction to Intellectual Property Rights",1,"","\u2014","\u2014","next"]
   ]},
   {id:"mgmt", name:"Department electives", need:2, rule:"Pick any two. 1 + 1.", courses:[
     ["EM5130","HR and Leadership",1,"","\u2014","\u2014","next"],
     ["EM5170","Design Thinking",1,"","\u2014","\u2014","next"],
     ["EM5160","Marketing Research",1,"","\u2014","\u2014","next"],
     ["EM5390","Start-up Financing",1,"","\u2014","\u2014","next"]
   ]},
   {id:"eng", name:"Engineering elective", need:3, rule:"Same rule as Semester 1.", eng:true, courses:[]},
   {id:"mand", name:"Mandatory", need:2, rule:"Both are required, not a choice. 1 + 1.", courses:[
     ["EM6096","Industry Lecture",1,"","\u2014","\u2014","next"],
     ["LA5180","Communication Skills (Liberal Arts)",1,"","\u2014","\u2014","next"]
   ]}
 ]}
};

var LATER=[["Semester 3","EM6085 Project Stage I — problem definition and business plan",12],
           ["Semester 4","EM6095 Project Stage II — build a prototype or proof of concept",12]];

/* ===== Engineering elective catalogue: 117 Level 5-6 courses, slots verified
   against published departmental timetables for Jul-Nov 2026 =====
   [code, slot, credits, title, department, aimsVerified3cr] */
var ENG=[
["AM5010","G","3.00","Fundamentals of Additive Manufacturing","Additive Manufacturing",1,0],
["AI1000","D","","Theory","Artificial Intelligence",0,1],
["AI2000","C","","of ML","Artificial Intelligence",0,1],
["AI2200","Q","","Inequalities","Artificial Intelligence",0,1],
["AI3000","S","","Learning","Artificial Intelligence",0,1],
["AI3403","Q","","Systems","Artificial Intelligence",0,1],
["AI4000","B","","","Artificial Intelligence",0,1],
["AI4403","S","","in Finance","Artificial Intelligence",0,1],
["AI5000","C","3.0","Foundations of Machine Learning","Artificial Intelligence",0,0],
["AI5030","S","3.0","Probability and Stochastic Processes","Artificial Intelligence",0,0],
["AI5040","R","","Game Theory and Mechanism Design","Artificial Intelligence",0,4],
["AI5100","D","3.0","Deep Learning","Artificial Intelligence",0,0],
["AI5110","F","3.0","Linear Algebra and Applications","Artificial Intelligence",0,0],
["BM1000","C","2","Physio-Anatomy-I","Biomedical Engineering",0,1],
["BM1060","F","3","Introduction to Programing and Elementory Data Structure","Biomedical Engineering",0,1],
["BM2013","G","3","Analong and intigrated Circuits","Biomedical Engineering",0,1],
["BM2053","C","2","Mathematical models & systems biology","Biomedical Engineering",0,1],
["BM3000","G","3","Natural intelligence, Foundations of","Biomedical Engineering",0,1],
["BM3040","B","2","Introduction to Biomechanics","Biomedical Engineering",0,1],
["BM3900","E","3","Linear Systems and Signal","Biomedical Engineering",0,1],
["BM4020","F","3","Biophotonics","Biomedical Engineering",0,1],
["BM4080","S","2","Medical image processing & analysis","Biomedical Engineering",0,1],
["BM4090","F","2","Biomaterials-1","Biomedical Engineering",0,1],
["BM4135","Q","2","Biomechanical Design","Biomedical Engineering",0,1],
["BM5013","Q","2","Sensors & transducers in healthcare","Biomedical Engineering",0,3],
["BM5023","R","2","Biomedical Device","Biomedical Engineering",0,3],
["BM5030","E","1","Scientific Computing","Biomedical Engineering",0,3],
["BM5033","D","2","Statistical Inference Methods in Bioengineering","Biomedical Engineering",0,3],
["BM5040","E","1","Biomechanics","Biomedical Engineering",0,3],
["BM5070","C","2","Systems Physiology","Biomedical Engineering",0,3],
["BM5090","F","1","Biomaterials: Materials in Medicine","Biomedical Engineering",0,3],
["BM5110","B","1","Lab on Chip","Biomedical Engineering",0,3],
["BM5190","G","2","Biofabrication","Biomedical Engineering",0,3],
["BM5193","B","1","Product Design and Prototyping","Biomedical Engineering",0,3],
["BT1020","C","","Bioinformatics","Biotechnology",0,1],
["BT1110","G","","to Bio-Nanotechnology","Biotechnology",0,1],
["BT2030","E","","","Biotechnology",0,1],
["BT2040","B","","","Biotechnology",0,1],
["BT2053","Q","","Data Biology and Biological Databases","Biotechnology",0,1],
["BT3030","R","","Alignment Algorithms","Biotechnology",0,1],
["BT3043","D","","Engineering","Biotechnology",0,1],
["BT3050","S","","Transcriptomics, Proteomics","Biotechnology",0,1],
["BT3123","P","","and R for Biologists","Biotechnology",0,1],
["BT3203","B","","Learning in Bioinformatics","Biotechnology",0,1],
["BT4010","R","","aided Drug Design","Biotechnology",0,1],
["BT4026","B","","in Biotechnology and Bioinformatics","Biotechnology",0,1],
["BT4030","C","","Biotechnology","Biotechnology",0,1],
["BT4040","S","","and Immunotechnology","Biotechnology",0,1],
["BT4150","A","","stability and human disease","Biotechnology",0,1],
["BT4223","F","","for Molecular Dynamics simulation","Biotechnology",0,1],
["BT5013","C","","Biochemistry","Biotechnology",0,4],
["BT5060","Q","","Genome Organization and Gene Regulation","Biotechnology",0,4],
["BT6040","G","","Bioindustry Lectures","Biotechnology",0,4],
["BT6060","P","","Protein Misfolding in Neurodegenerative Diseases","Biotechnology",0,4],
["BT6070","R","","Molecular mechanisms of aging and age-related disorders","Biotechnology",0,4],
["BT6113","E","","Structural Bioinformatics","Biotechnology",0,4],
["BT6143","F","","Gene Technology","Biotechnology",0,4],
["BT6303","S","","Proteomics: Techniques and  Applications","Biotechnology",0,4],
["BT6390","D","","Advanced Cell Biology","Biotechnology",0,4],
["BT6630","A","","RNA Biology and Therapeutics","Biotechnology",0,4],
["BT6873","B","","Host-Pathogen-Microbiota Interaction","Biotechnology",0,4],
["CH1110","C","","to Chemical Engg","Chemical Engineering",0,1],
["CH1120","E","","Chemistry","Chemical Engineering",0,1],
["CH2110","A","","Engineering","Chemical Engineering",0,1],
["CH2120","F","3","Nuerical Method","Chemical Engineering",0,1],
["CH2130","P","","Phenomena","Chemical Engineering",0,1],
["CH2140","C","","Engg Thermodynamics","Chemical Engineering",0,1],
["CH2150","B","","Mathematics in Chemical Engineering","Chemical Engineering",0,1],
["CH3110","A","","Transfer- I","Chemical Engineering",0,1],
["CH3120","F","","Operations","Chemical Engineering",0,1],
["CH3130","D","","Technology","Chemical Engineering",0,1],
["CH3140","B","","Reaction Engineering - II","Chemical Engineering",0,1],
["CH4112","B","","Design and Economics","Chemical Engineering",0,1],
["CH5010","A","","Advanced Numerical Methods","Chemical Engineering",0,4],
["CH5050","B","","Heterogeneous Catalytic Reaction Engineering","Chemical Engineering",0,4],
["CH5060","G","","Advanced Process Control","Chemical Engineering",0,4],
["CH5400","C","","Introduction to Colloids and Interface Science","Chemical Engineering",0,4],
["CH5440","D","","Materials for Soft Robots","Chemical Engineering",0,4],
["CH5460","D","","Process Integration","Chemical Engineering",0,4],
["CH5480","C","","Advanced Colloids and Interfaces","Chemical Engineering",0,4],
["CH5500","E","","Introduction to Polymer Rheology","Chemical Engineering",0,4],
["CH5710","E","","Machine Learning Fundamentals","Chemical Engineering",0,4],
["CH5720","P","","AI/ML Tool Chains for Chemical Engineers","Chemical Engineering",0,4],
["CH5730","Q","","Computer Vision in Chemical and Life Sciences","Chemical Engineering",0,4],
["CH5740","F","","DFT/AI for Catalyst Design","Chemical Engineering",0,4],
["CH5750","C","","Accelerating MD with AI/ML","Chemical Engineering",0,4],
["CH5860","P","","Computational Biology","Chemical Engineering",0,4],
["CH5900","Q","","Computational Fluid Dynamics","Chemical Engineering",0,4],
["CH5910","D","","Chemical Reactor Modeling","Chemical Engineering",0,4],
["CH6080","E","","Introduction to Cardiovascular Mechanics","Chemical Engineering",0,4],
["CH6580","E","","Advanced Mineral Processing","Chemical Engineering",0,4],
["CH6620","F","","Intermolecular Forces","Chemical Engineering",0,4],
["CH6870","P","","Machine learning for process systems engineering","Chemical Engineering",0,4],
["CH6910","F","","Physicochemical Fundamentals for Chemical Engineers","Chemical Engineering",0,4],
["CY1010","P","2","Environmental Chemistry","Chemistry",0,1],
["CY5010","P","","Reaction Mechanism and Rearrangements","Chemistry",0,2],
["CY5060","B","","solid-state chemistry and formulation tec","Chemistry",0,2],
["CY5110","F","","in Inorganic Chemistry","Chemistry",0,2],
["CY5210","R","","and Chemical Kinetics","Chemistry",0,2],
["CY5220","S","","State Chemistry (+PhD)","Chemistry",0,2],
["CY5240","Q","","Chemistry & Molecular Spectroscopy (+PhD)","Chemistry",0,2],
["CY6010","A","","Methodology in Organic Chemistry (+PhD)","Chemistry",0,2],
["CY6110","G","","in Biological Systems (+PhD)","Chemistry",0,2],
["CY6120","G","","Organometallic Chemistry","Chemistry",0,2],
["CY6220","C","","Methods in Chemistry (+PhD)","Chemistry",0,2],
["CY6700","D","","& Applications (Elective) (+ PhD)","Chemistry",0,2],
["CY6730","B","","Molecular Spectroscopy(+PhD)","Chemistry",0,2],
["CY6750","E","","Storage Devices","Chemistry",0,2],
["CY6903","P","","Modeling of Complex Chemical Systems(+PhD)","Chemistry",0,2],
["CE2130","F","3","","Civil Engineering",0,1],
["CE2420","E","3","Fluid Mechanics","Civil Engineering",0,1],
["CE2510","C","3","","Civil Engineering",0,1],
["CE2600","A","1","Sustainability in Civil","Civil Engineering",0,1],
["CE2900","G","2","","Civil Engineering",0,1],
["CE3212","B","3","Reinforced Concrete Design","Civil Engineering",0,1],
["CE3242","D","3","Structural Steel Design","Civil Engineering",0,1],
["CE3330","G","3","Foundation Engineering","Civil Engineering",0,1],
["CE3400","A","2","Engineering Hydrology","Civil Engineering",0,1],
["CE3820","E","2","Highway Design and Materials","Civil Engineering",0,1],
["CE4400","D","2","Water Resource Engineering","Civil Engineering",0,1],
["CE4830","C","1","","Civil Engineering",0,1],
["CE5170","S","3","Mathematical Methods in Civil Engineering","Civil Engineering",0,0],
["CE5190","Q","3","Advanced Concrete Technology","Civil Engineering",0,0],
["CE5220","P","3.00","Solid Waste Management","Civil Engineering",1,0],
["CE5290","P","3","Applied Elasticity and Plasticity","Civil Engineering",0,0],
["CE5352","P","3","Design of Earth Structures","Civil Engineering",0,0],
["CE5730","Q","3","Planning","Civil Engineering",0,0],
["CE6243","R","3.00","Life Cycle Sustainability Analysis","Civil Engineering",1,0],
["CE6500","R","3","Engineering Hydrology and Hydrologic Systems","Civil Engineering",0,0],
["CE6520","Q","2","Irrigation Water Management","Civil Engineering",0,3],
["CE6710","P","3","and ITS","Civil Engineering",0,0],
["CE6720","G","3","Advanced Pavement Materials","Civil Engineering",0,0],
["CC1010","A","1.0","Introduction to Climate Change","Climate Change",0,1],
["CC5140","S","2.0","Climate governance","Climate Change",0,3],
["CC5200","P","3.0","Remote Sensing, GIS & Climate Change","Climate Change",0,0],
["CC5320","D","3.00","Introduction to Climate Science and Climate Monitoring","Climate Change",1,0],
["CC5350","R","3.0","Translational Science for Collaborative Research","Climate Change",0,0],
["CC5360","Q","3.0","Applied Mathematics and Scientific Computing for Climate Change","Climate Change",0,0],
["CC5370","F","2.0","Essentials of Meteorology","Climate Change",0,3],
["CC5380","F","1.0","Paleoclimatology: a peek into ancient climate change","Climate Change",0,3],
["CS1000","E","1.0","Introduction to computing","Computer Science & Engineering",0,1],
["CS1010","C","","Maths for Computer Science","Computer Science & Engineering",0,1],
["CS2233","C","","Structures","Computer Science & Engineering",0,1],
["CS2323","E","3.0","Computer Architecture","Computer Science & Engineering",0,1],
["CS3390","R","","of Machine Learning","Computer Science & Engineering",0,1],
["CS3423","B","","II","Computer Science & Engineering",0,1],
["CS3510","Q","1.0","Operating Systems I","Computer Science & Engineering",0,1],
["CS3530","A","","Networks","Computer Science & Engineering",0,1],
["CS3550","R","","","Computer Science & Engineering",0,1],
["CS5013","C","","GPU Programming","Computer Science & Engineering",0,4],
["CS5060","P","","Advanced Computer Networks","Computer Science & Engineering",0,4],
["CS5103","R","","Practical Malware Analysis","Computer Science & Engineering",0,4],
["CS5280","F","3.0","Concurrency Control in Transactional Systems","Computer Science & Engineering",0,0],
["CS5363","S","","Advanced Computer Architecture","Computer Science & Engineering",0,4],
["CS5590","D","3","FoML","Computer Science & Engineering",0,0],
["CS5600","F","","Data Mining","Computer Science & Engineering",0,4],
["CS5610","E","","Computational Number Theory and Algebra","Computer Science & Engineering",0,4],
["CS5663","Q","","AI for Databases","Computer Science & Engineering",0,4],
["CS5903","S","","Distributed AI Training in a large-scale GPU cluster","Computer Science & Engineering",0,4],
["CS6013","G","3.0","Advanced Data Structures and Algorithms","Computer Science & Engineering",0,0],
["CS6113","P","","Representation Learning","Computer Science & Engineering",0,4],
["CS6160","A","","Cryptology","Computer Science & Engineering",0,4],
["CS6843","D","","C4ML: Compilers for Machine Learning","Computer Science & Engineering",0,4],
["DS3813","R","3.0","Basics of Design","Design",0,1],
["EE1010","P","","for Electrical Engineers","Electrical Engineering",0,1],
["EE1030","D","3.0","Matrix Theory","Electrical Engineering",0,1],
["EE1101","E","3.0","Circuits and Network Analysis","Electrical Engineering",0,1],
["EE1202","C","3.0","Digital Circuits","Electrical Engineering",0,1],
["EE1206","E","","Systems and Signal Processing","Electrical Engineering",0,1],
["EE2000","C","","Processing","Electrical Engineering",0,1],
["EE2080","D","","Processes","Electrical Engineering",0,1],
["EE2100","D","","Theory","Electrical Engineering",0,1],
["EE2104","E","","Device Fundamentals","Electrical Engineering",0,1],
["EE2200","B","","Machines","Electrical Engineering",0,1],
["EE2503","Q","","methods for device modeling","Electrical Engineering",0,1],
["EE2510","Q","","tools for IC design","Electrical Engineering",0,1],
["EE3004","E","","trends in EE","Electrical Engineering",0,1],
["EE3140","E","","and Antennas","Electrical Engineering",0,1],
["EE3150","C","","digital design","Electrical Engineering",0,1],
["EE3300","A","","Circuits","Electrical Engineering",0,1],
["EE3301","C","","VLSI Design","Electrical Engineering",0,1],
["EE3501","Q","","Electronics","Electrical Engineering",0,1],
["EE3502","B","","Design Tapeout","Electrical Engineering",0,1],
["EE3510","F","","design and verification","Electrical Engineering",0,1],
["EE3520","A","","IC Design","Electrical Engineering",0,1],
["EE3700","P","","Systems","Electrical Engineering",0,1],
["EE4500","S","","Systems","Electrical Engineering",0,1],
["EE4502","F","","design test and characterization","Electrical Engineering",0,1],
["EE5033","R","","IoT","Electrical Engineering",0,4],
["EE5110","E","","Semiconductor Device and Modeling","Electrical Engineering",0,4],
["EE5170","S","","Embedded Programming","Electrical Engineering",0,4],
["EE5182","B","3.00","VLSI Technology","Electrical Engineering",1,0],
["EE5183","A","","Analog IC Design","Electrical Engineering",0,4],
["EE5193","C","","CMOS Digital Design","Electrical Engineering",0,4],
["EE5200","G","","Steady State Power System Analysis","Electrical Engineering",0,4],
["EE5210","C","","Power Converter Design","Electrical Engineering",0,4],
["EE5230","P","","Power System Dynamics and Control","Electrical Engineering",0,4],
["EE5240","Q","","Electric Machine Analysis and Control","Electrical Engineering",0,4],
["EE5350","F","","Error Correcting Codes","Electrical Engineering",0,4],
["EE5480","A","","Introduction to State Space","Electrical Engineering",0,4],
["EE5490","A","","State Estimation","Electrical Engineering",0,4],
["EE5540","R","","Optimal Control","Electrical Engineering",0,4],
["EE5552","S","","Memory Design","Electrical Engineering",0,4],
["EE5604","D","","Introduction to Statistical Learning Theory","Electrical Engineering",0,4],
["EE5609","F","3.0","Matrix Theory","Electrical Engineering",0,0],
["EE5610","C","","Pattern Recognition and Machine Learning","Electrical Engineering",0,4],
["EE5630","D","","Topics in Signal Processing","Electrical Engineering",0,4],
["EE5670","A","","High speed Semiconductor Optoelectronics","Electrical Engineering",0,4],
["EE5750","Q","","Quantum Error Correction","Electrical Engineering",0,4],
["EE5817","S","","Random Variables and Stochastic Processes","Electrical Engineering",0,4],
["EE5837","D","3.00","Principles of Digital Communication","Electrical Engineering",1,0],
["EE5848","P","","Topics in Information Theory and Coding","Electrical Engineering",0,4],
["EE5900","B","","Advanced Digital Signal Processing","Electrical Engineering",0,4],
["EE6190","R","","Introduction to Advanced Packaging","Electrical Engineering",0,4],
["EE6307","C","","Speech Systems","Electrical Engineering",0,4],
["EE6380","S","","Deep Learning","Electrical Engineering",0,4],
["ET5010","B","2.0","Fundamentals of Electrochemistry","Energy Science & Technology",0,3],
["ET5020","E","3.00","Electrochemical Energy Storage Systems: Batteries, Fuel Cells and Supe","Energy Science & Technology",1,0],
["ET5030","R","2.0","Non-conventional energy sources and environment","Energy Science & Technology",0,3],
["ET5060","A","2.0","Bio-energy","Energy Science & Technology",0,3],
["EP1108","A","2","Modern Physics","Engineering Physics",0,1],
["EP1118","D","2","Maths for Physics","Engineering Physics",0,1],
["EM4040","Q","","Startup","Entrepreneurship & Management",0,1],
["EM5010","Q","","Strategy for Startup","Entrepreneurship & Management",0,2],
["EM5013","E","","Analytics","Entrepreneurship & Management",0,2],
["EM5020","P","","Management","Entrepreneurship & Management",0,2],
["EM5040","E","","Theory for Startups","Entrepreneurship & Management",0,2],
["EM5050","P","","Modelling","Entrepreneurship & Management",0,2],
["EM5090","Q","","and Finance for Entrepreneurs","Entrepreneurship & Management",0,2],
["EM5110","G","","of Techno-entrepreneurship","Entrepreneurship & Management",0,2],
["EM5180","C","","for Engineers","Entrepreneurship & Management",0,2],
["EM5270","R","","Marketing","Entrepreneurship & Management",0,2],
["EM6080","S","","for New Ventures","Entrepreneurship & Management",0,2],
["EM6980","C","","Research Methodology","Entrepreneurship & Management",0,2],
["IC1010","C","","Organic Chemistry-I","Integrated Circuits & Microsystems",0,1],
["IC2010","E","","Organic Chemistry-II","Integrated Circuits & Microsystems",0,1],
["IC2020","C","","to Biochemistry","Integrated Circuits & Microsystems",0,1],
["IC2030","S","","","Integrated Circuits & Microsystems",0,1],
["IC2060","Q","","and Petrochemicals","Integrated Circuits & Microsystems",0,1],
["IC3010","B","","Science-I","Integrated Circuits & Microsystems",0,1],
["IC3020","A","","Energy Conversion","Integrated Circuits & Microsystems",0,1],
["IC3030","R","","Kinetics and Surface Chemistry","Integrated Circuits & Microsystems",0,1],
["IC4010","D","","to Drug Design","Integrated Circuits & Microsystems",0,1],
["IC4020","F","","Science-II","Integrated Circuits & Microsystems",0,1],
["IC4030","C","","Science-II","Integrated Circuits & Microsystems",0,1],
["ID1006","F","","for Engineering Education","Interdisciplinary",0,1],
["ID1063","F","3.0","Introduction to Programming Theory","Interdisciplinary",0,1],
["ID2230","A","","Structures & Applications","Interdisciplinary",0,1],
["LA1760","G","","Skills","Liberal Arts",0,1],
["LW5030","D","3.00","Fundamentals of Light Weight Alloys","Light Weight Materials",1,0],
["MS1830","C","2.0","Fundamentals of Physical Metallurgy","Materials Science & Metallurgy",0,1],
["MS1980","E","2.0","Fundamental of scientific computing","Materials Science & Metallurgy",0,1],
["MS1990","C","1.0","Introduction to Material science and Engineering","Materials Science & Metallurgy",0,1],
["MS2860","S","2.0","Computational Methods in Material Science","Materials Science & Metallurgy",0,1],
["MS2970","P","3.0","Materials thermodynamics and kinetics","Materials Science & Metallurgy",0,1],
["MA2110","D","1","Probability","Mathematics",0,1],
["MA2120","D","1","Transforms Techniques","Mathematics",0,1],
["MA2150","D","","to Metric Spaces","Mathematics",0,1],
["MA2550","F","3.0","Linear Algebra","Mathematics",0,1],
["MA3060","A","","Analysis","Mathematics",0,1],
["AE3110","C","3","","Mechanical & Aerospace",0,1],
["AE3120","P","3","","Mechanical & Aerospace",0,1],
["AE5110","S","3","Aerodynamics and Propulsion","Mechanical & Aerospace",0,0],
["AE5120","R","3","Flight Dynamics and Structures","Mechanical & Aerospace",0,0],
["ME1060","C","3","","Mechanical & Aerospace",0,1],
["ME2050","Q","2","","Mechanical & Aerospace",0,1],
["ME3010","G","2","","Mechanical & Aerospace",0,1],
["ME3030","S","3.0","Modelling and Simulation","Mechanical & Aerospace",0,1],
["ME3040","B","1.5","","Mechanical & Aerospace",0,1],
["ME3050","B","1.5","","Mechanical & Aerospace",0,1],
["ME3140","D","3","","Mechanical & Aerospace",0,1],
["ME3160","B","2","","Mechanical & Aerospace",0,1],
["ME3170","A","3","","Mechanical & Aerospace",0,1],
["ME3180","R","3.0","FEM and CFD Theory","Mechanical & Aerospace",0,1],
["ME3210","A","3","","Mechanical & Aerospace",0,1],
["ME3220","C","3","","Mechanical & Aerospace",0,1],
["ME5010","F","3","Mathematical Methods for Engineers","Mechanical & Aerospace",0,0],
["ME5020","C","1.5","","Mechanical & Aerospace",0,3],
["ME5080","C","1.5","","Mechanical & Aerospace",0,3],
["ME5110","P","3","Advanced Mechanics of Solids","Mechanical & Aerospace",0,0],
["ME5120","D","3","Dynamics and Vibration","Mechanical & Aerospace",0,0],
["ME5130","Q","3","Finite Element Method","Mechanical & Aerospace",0,0],
["ME5210","B","3","CAD/CAM","Mechanical & Aerospace",0,0],
["ME5310","Q","3","Incompressible Fluid Flow","Mechanical & Aerospace",0,0],
["ME5320","E","3","Advanced Heat Transfer","Mechanical & Aerospace",0,0],
["ME5330","P","3","Computational Fluid Dynamics","Mechanical & Aerospace",0,0],
["ME5340","B","3","IC Engine Combustion and Pollution","Mechanical & Aerospace",0,0],
["ME5480","S","3","Sustainable Energy Technology: Energy Sources, Efficiency, Storage and","Mechanical & Aerospace",0,0],
["ME5770","C","3","Fundamentals of Robotics","Mechanical & Aerospace",0,0],
["ME5780","D","3","Control Systems Design","Mechanical & Aerospace",0,0],
["ME5880","A","3","","Mechanical & Aerospace",0,0],
["ME5890","R","3","Advanced Refrigeration and Thermal Systems","Mechanical & Aerospace",0,0],
["ME6040","E","3","Machine Learning and Its Applications","Mechanical & Aerospace",0,0],
["SD5010","R","3.00","Fundamentals of Semiconductor Materials","Semiconductor Materials & Devices",1,0],
["SD5113","C","3.00","Vacuum Technology in Semiconductor","Semiconductor Materials & Devices",1,0],
["SM5033","S","2.0","Internet of Things (IoT)","Smart Mobility",0,3],
["SE5500","F","","Green Chemistry and Industrial Processes","Sustainable Engineering",0,4],
["SE5723","A","","Concepts in Sustainable Engineering","Sustainable Engineering",0,4]
];
/* index 6 — why it cannot be your engineering elective */
var WHYTXT=["","Undergraduate or PhD level \u2014 yours must start with 5 or 6","This department is excluded for your engineering elective","Not a 3-credit course","Credits not published \u2014 confirm in AIMS"];


/* ===== plain-language glossary — every term that stops a newcomer ===== */
var GLOSS={
 "slot":["Slot","A letter that fixes when a course meets. A–G are one-hour slots, P–S are ninety-minute ones. Every course sits in exactly one. Two courses in the same letter always clash, and no instructor will move one for you."],
 "segment":["Segment","The semester is six blocks of about 2.5 to 3 weeks. A course’s segment code says which blocks it spans: 1–6 is the whole semester, 1–2 is just the first two blocks. It decides your drop deadline."],
 "credit":["Credit","Roughly 14 teaching hours. A 3-credit course runs the full semester at about 42 hours; a 1-credit course is two segments. Semester 1 is 14 credits total."],
 "elective type":["Elective type","The category you file a course under in the AIMS form. There are 14 options and no guidance. Choose wrong and your whole submission can be rejected, so this planner tells you which one to pick for each course."],
 "core":["Core","Compulsory. You do not choose these, and you cannot swap them for something else."],
 "fa":["Faculty Advisor (FA)","Dr. Ranapratap Maradana. He approves your registration and every add or drop after it. Nothing goes through without him, so leave time."],
 "dpgc":["DPGC","Departmental Postgraduate Committee, convened by Dr. Nakul Parameswar. The person to email when a course is missing from AIMS or a rule is unclear."],
 "type conversion":["Type conversion","A one-time, irreversible change of an elective from one category to another, capped at 3 credits. You submit a form. The department is explicit that it cannot be repeated."],
 "audit":["Audit","Attend a course without the grade counting toward your CGPA. Shows as AU on the transcript. Needs the instructor’s permission."],
 "backlog":["Backlog","A course you failed and are retaking. It goes in a separate section of the AIMS registration form, not the Regular one."],
 "fractal":["Fractal system","IITH splits subjects into small modules, so a 1-credit overview of a topic can grow into a deeper 2 or 3-credit course later. It is why your electives are 1 credit each rather than one big block."],
 "challenge lectures":["Challenge Lectures","Wednesday afternoon is reserved institute-wide for these. It is why slot F is the odd one — two mornings plus a Wednesday afternoon, where every other letter has three mornings."],
 "clean india":["Clean India","A mandatory non-credit course run by NSS, handled outside AIMS course registration. Watch for a separate email; it does not appear in your registration form."],
 "engineering elective":["Engineering elective","A 3-credit course from another department, chosen by you. Course code must start with 5 or 6. Design, Physics, Chemistry and Maths are excluded. Talk to your FA before choosing."],
 "picker":["Course picker","The search popup inside the AIMS registration form. It only opens after you have chosen an elective type, and it shows 596 of the 786 courses actually running."],
 "cgpa":["CGPA","Your running average across every course so far, weighted by credits. Grades run A+ and A at 10 points, then A- 9, B 8, B- 7, C 6, C- 5, D 4, and F at zero."]
};

var CODEPARTS=[
 ["Letters","Department offering the course. EM is Entrepreneurship &amp; Management, ME is Mechanical, CS is Computer Science."],
 ["1st digit","Level. 1–4 are undergraduate years, 5–6 are Masters, 7–8 are PhD. Your engineering elective must be 5 or 6."],
 ["2nd digit","Nature. 0 theory, 1 lab, 2 design, 3 theory+lab, 4 design+tutorial, 5 project or thesis, 6 seminar."],
 ["3rd–4th","Just an identifier. No meaning."]
];

var MISTAKES=[
 ["Registering into the wrong semester","Three terms show as “Open” in AIMS at the same time — JUL26-NOV26, the 2026 summer term, and last year’s JUL25-NOV25. Nothing highlights the current one.","This planner only ever describes JUL26-NOV26, and the AIMS steps tell you exactly which row to click."],
 ["Picking the wrong elective type","Fourteen options, no explanation, and the same course list under every one. The wrong choice can get your entire submission rejected after you have waited for approval.","Every course group here tells you the exact type to file it under, and the pre-flight script repeats it row by row."],
 ["A plan that falls apart at registration","The registration form never shows a slot next to a course, so you build your plan blind. AIMS does warn you when courses clash — but by then the whole plan is assembled around the clashing pair and you are redoing it against the deadline.","Clashes are flagged the moment they happen, and clashing options are hidden from the picker by default."],
 ["Choosing a course that is not allowed","The engineering elective must be Level 5 or 6 and cannot come from Design, Physics, Chemistry or Maths. AIMS enforces none of this.","Every course is labelled with whether you can actually pick it, and anything you add by hand is checked against both rules."],
 ["Assuming a course exists because it is on the curriculum sheet","The AIMS picker shows 596 of the 786 courses running this term. A course can be printed on your curriculum sheet, timetabled by the department, and still return \u201cNo records found\u201d when you search for it.","Anything known to be missing is labelled here. If a code returns nothing in AIMS, that is the department\u2019s to fix \u2014 email the DPGC the same day."],
 ["Missing the real deadline","The department email says 3 August. Every course record in AIMS says registration closes 31 July at 23:59. If you trust the email you lose three days you never had.","The earlier date is the one shown everywhere, and it goes into your calendar with a reminder."],
 ["Thinking you are done when you press Register","Your Faculty Advisor still has to approve it, and a rejection appears in a collapsed list at the bottom of the page that is easy to never look at.","The pre-flight checklist ends with going back to check, not with pressing the button."],
 ["Forgetting the non-credit course","Clean India is mandatory, is run by NSS, and never appears in course registration. Students who only work from the AIMS form miss it entirely.","It is on the checklist."]
];


/* ===== what each course actually teaches =====
   Every entry was read from a published IITH source. Nothing is inferred from a
   course title. [summary, sourceLabel, sourceURL, prerequisiteOrNull] */
var DESC={
"AI5040":["Non-cooperative game theory (strategic and extensive form games, Nash equilibrium, bargaining), cooperative game theory (the core, Shapley value, nucleolus), mechanism design (Arrow's impossibility, VCG mechanisms, Myerson auctions), and applications to fair division, routing games and sponsored search auctions.","Instructor course site","https://sites.google.com/ai.iith.ac.in/ai5040-gtmd/home",null],
"AI5100":["Deep feedforward networks, regularisation and optimisation for deep models, convolutional and recurrent networks, practical methodology, then advanced topics including GANs and variational autoencoders. Recent instructor pages add attention and Transformers, diffusion models and CLIP.","Institute Courses of Study","https://www.iith.ac.in/assets/files/pdf/Courses-of-Study-Bachelors.pdf",null],
"AI5000":["Published under its older title “Basics of Machine Learning”: classification and regression with linear and nonlinear models, Bayes decision theory, risk minimisation, multilayer perceptrons and support vector machines, unsupervised learning, Bayesian networks and graphical models, exact and approximate inference, parameter estimation.","Institute Courses of Study","https://www.iith.ac.in/assets/files/pdf/Courses-of-Study-Bachelors.pdf",null],
"ME5480":["Thermodynamics review; energy demand and supply outlook; climate projections and risk; non-renewables and their environmental impact; renewables (wind, solar PV and thermal, geothermal, hydro); carbon-neutral fuels (biomass, hydrogen, CO2-to-fuel, fuel cells); energy storage (battery, electro-mechanical, thermal); efficiency and emissions (exergy optimisation, carbon capture, energy-efficient buildings, life-cycle assessment, smart grids).","MAE Courses Syllabus Manual","https://mae.iith.ac.in/files/mae_pg.pdf",null],
"ME5010":["Vectors and tensors, ordinary and partial differential equations, Fourier analysis, linear algebra including eigenvalues, orthogonalisation and SVD, integral equations, and the calculus of variations.","MAE Courses Syllabus Manual","https://mae.iith.ac.in/files/mae_pg.pdf","GATE-level mathematics"],
"ME5120":["Analytical dynamics, degrees of freedom, equations of motion via Newton's laws and Lagrange's equations, constrained motion, damped and undamped single- and multi-degree-of-freedom systems, vibration isolation, and vibration of continuous systems.","MAE Courses Syllabus Manual","https://mae.iith.ac.in/files/mae_pg.pdf",null],
"ME5780":["System modelling and block diagrams, performance specifications and stability, PID and lead-lag controller design, root locus, state-space modelling, and state-space observers and controllers.","IITH CCE course page","https://cce.iith.ac.in/live_stream/jul-nov-2026/Control%20Systems%20Design.html","None stated"],
"EE5182":["Crystal growth and defects, wafer cleaning and wet etching, diffusion and ion implantation, oxidation kinetics and high-k dielectrics, lithography, chemical vapour deposition and epitaxy, metallisation and interconnects, plasma and rapid thermal processing, and process integration for NMOS, CMOS and bipolar.","EE department course page","https://ee.iith.ac.in/Courses/EE5182.html",null],
"EE5837":["Digital sources and quantisation, waveform channels and baseband transmission, signal-space representation, Gaussian noise, modulation and demodulation with receiver performance for BPSK, QAM and FSK, channel capacity, channel coding with convolutional and LDPC codes, and fading in wireless channels.","EE department course page","https://ee.iith.ac.in/Courses/EE5837.html",null],
"EE5610":["Parameter estimation, overfitting and model selection, the curse of dimensionality and bias-variance tradeoff, density estimation and Bayes decision theory, generative versus discriminative models, linear and logistic regression, K-means and vector quantisation, Gaussian mixtures, autoencoders, dimensionality reduction, hidden Markov models and linear dynamical systems.","EE department course page","https://ee.iith.ac.in/Courses/EE5610.html",null],
"CS5600":["Recommendation systems, information extraction, frequent pattern mining, finding similar items with LSH, stream mining, social network analysis, opinion mining, large-scale file systems and MapReduce, mining time series and discrete sequences, clustering, anomaly detection and mining web data.","CSE department elective sheet","https://cse.iith.ac.in/academics/courses.html",null],
"CS6013":["Divide and conquer including Strassen and FFT, greedy algorithms with minimum spanning trees and union-find, dynamic programming, probabilistic data structures, red-black and B-trees, heaps and amortised analysis, graph algorithms, NP-hardness, approximation and randomised algorithms.","Instructor course pages","https://people.iith.ac.in/aravind/cs6013.html",null],
"CE6500":["Governing equations for hydrologic processes; occurrence, distribution, measurement and interpretation of precipitation, abstractions, run-off, stream flow and groundwater; distributed and lumped hydrologic analysis; hydrologic statistics; and analysis of extreme events.","Institute Courses of Study, Masters and PhD","https://www.iith.ac.in/assets/files/pdf/Courses-of-Study-Masters-PhD.pdf",null],
"CE5170":["Vector and matrix operations and norms, tensor theory, Laplace transforms, Fourier series and transforms, first- and second-order ODEs with initial and boundary value problems, PDE classification and analytical solutions, numerical integration and differentiation, root-finding, curve fitting, and linear systems by Gaussian elimination, Gauss-Seidel, LU, eigenvalue analysis, SVD and least squares.","IITH CCE course page","https://cce.iith.ac.in/live_stream/july-nov-2025/Mathematical-Methods-in-Civil-Engineering.html","Basics of linear algebra"],
"CH5010":["Review of computer programming; solving simultaneous linear and nonlinear equations; Newton's interpolation; quadrature; systems of first-order ODEs and stability analysis; variable step-size algorithms; finite difference methods for ODEs and for hyperbolic, parabolic and elliptic PDEs; and numerical solutions to chemical engineering problems in separation, reaction engineering, fluid mechanics, process control and thermodynamics.","ChE department course list","https://che.iith.ac.in/courseb-list-22-07-2024.html",null],
"BT6390":["Introduction to cell biology, plasma membrane biogenesis and function, the cytoskeleton, mitosis and meiosis, mitochondrial biogenesis, protein import, ER and Golgi biosynthesis, vesicular trafficking, lysosome biogenesis and pathophysiology, the nuclear envelope and nuclear transport, the cell cycle and cell death, and regulation of signalling pathways.","Biotechnology department course descriptions","https://sites.google.com/iith.ac.in/department-of-biotechnology/academics/courses",null],
"SE5723":["Sustainability and its social, environmental and economic components; sustainability concepts through life-cycle assessment, resource allocation, the materials cycle, energy balance, impact and risk analysis and environmental cost analysis; sustainable routes including waste management, pollution abatement and resource recovery; the UN Sustainable Development Goals; plus lab sessions on LCA and resource-flow software and circular economy.","Greenko School SE curriculum","https://gss.iith.ac.in/Program.html",null],
"ME5110":["Published in the MAE syllabus manual alongside the other Mechanical PG courses.","MAE Courses Syllabus Manual","https://mae.iith.ac.in/files/mae_pg.pdf",null],
"ME5130":["Published in the MAE syllabus manual alongside the other Mechanical PG courses.","MAE Courses Syllabus Manual","https://mae.iith.ac.in/files/mae_pg.pdf",null],
"ME5210":["Published in the MAE syllabus manual alongside the other Mechanical PG courses.","MAE Courses Syllabus Manual","https://mae.iith.ac.in/files/mae_pg.pdf",null],
"ME5310":["Published in the MAE syllabus manual alongside the other Mechanical PG courses.","MAE Courses Syllabus Manual","https://mae.iith.ac.in/files/mae_pg.pdf",null],
"ME5320":["Published in the MAE syllabus manual alongside the other Mechanical PG courses.","MAE Courses Syllabus Manual","https://mae.iith.ac.in/files/mae_pg.pdf",null],
"ME5330":["Published in the MAE syllabus manual alongside the other Mechanical PG courses.","MAE Courses Syllabus Manual","https://mae.iith.ac.in/files/mae_pg.pdf",null],
"ME5340":["Published in the MAE syllabus manual alongside the other Mechanical PG courses.","MAE Courses Syllabus Manual","https://mae.iith.ac.in/files/mae_pg.pdf",null],
"ME6040":["Published in the MAE syllabus manual alongside the other Mechanical PG courses.","MAE Courses Syllabus Manual","https://mae.iith.ac.in/files/mae_pg.pdf",null]
};

/* codes whose published title disagrees between the 2026 departmental timetable and an
   older institute catalogue. IITH reuses codes, so both may have been right at some point. */
var TITLECONFLICT={
"AI5110":"The Jul–Nov 2026 AI timetable prints this as “Linear Algebra and Applications”. The institute Courses of Study prints AI5110 as “Big Data – Tools and Techniques”, 2 credits. Confirm which one is running before you register.",
"BT5013":"The Jul–Nov 2026 Biotechnology timetable prints this code. The department's own course document lists Biochemistry as BT5010. Confirm the code in AIMS.",
"ME5880":"The MAE syllabus manual calls this “Combustion and Flow Diagnostics”; the current MAE stream page calls it “Probability and Optimization”. No title is shown here until the department confirms.",
"SE5723":"Published in the Greenko School curriculum as SE50723. Confirm the exact code in AIMS.",
"ET5020":"The Energy Science M.Tech lists “Electrochemical energy storage systems” as a core course, but no IITH page publishes the code ET5020. Confirm before registering."
};
